# Generated by Django 2.0.2 on 2018-03-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_kairos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
