# Generated by Django 2.0.2 on 2018-03-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_kairos', '0002_auto_20180312_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
