# Generated by Django 2.0.2 on 2018-03-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_kairos', '0004_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
