# Generated by Django 2.0.2 on 2018-03-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_kairos', '0005_auto_20180313_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
