# Generated by Django 2.0.2 on 2018-03-14 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('face_kairos', '0007_auto_20180313_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
