# Generated by Django 2.0.2 on 2018-03-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_kairos', '0009_auto_20180315_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
