# Generated by Django 2.0.2 on 2018-03-28 01:52

from django.db import migrations, models
import face_kairos.models


class Migration(migrations.Migration):

    dependencies = [
        ('face_kairos', '0011_auto_20180325_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=60, validators=[face_kairos.models.validate_text]),
        ),
    ]
