# Generated by Django 2.0.2 on 2018-03-28 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_kairos', '0012_auto_20180327_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(5, message='Please enter a correct name')]),
        ),
    ]
