# Generated by Django 2.0.2 on 2018-03-28 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_kairos', '0013_auto_20180327_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
